library;

import 'package:flutter/material.dart';

import '../domain/contracts/media_adapter.dart';
import '../domain/contracts/session_store.dart';
import '../domain/errors/cerqle_exception.dart';
import '../domain/events/chat_event.dart';

part '../diagnostics/diagnostic_event.dart';
part 'presentation_config.dart';
part 'theme_data.dart';
part 'user.dart';

/// Immutable options used to create a Cerqle client or prebuilt chat UI.
///
/// The [widgetKey] is a public routing identifier. It is not a secret. Identity
/// signatures must be generated by the integrating application's server and
/// supplied through [user].
@immutable
class CerqleConfig {
  /// Creates package configuration for one Cerqle widget.
  const CerqleConfig({
    required this.widgetKey,
    this.apiBaseUrl = 'https://cerqle.ai',
    this.user,
    this.theme,
    this.useApiColors = true,
    this.lightStatusBarIcons = false,
    this.presentation = CerqlePresentation.fullScreen,
    this.enableTyping = true,
    this.mediaAdapter,
    this.diagnostics,
    this.oneSignalAppId = defaultOneSignalAppId,
    this.enableOneSignal = true,
    this.sessionStore,
  });

  /// Default OneSignal App ID used across Cerqle ecosystem.
  static const String defaultOneSignalAppId =
      'd507871c-ac7a-4aba-aa2d-ee93a0102f17';

  /// Public widget routing key issued by Cerqle.
  final String widgetKey;

  /// API origin used for widget requests.
  final String apiBaseUrl;

  /// Optional visitor profile and server-generated verified identity.
  final CerqleUser? user;

  /// Host presentation overrides for the prebuilt UI.
  final CerqleThemeData? theme;

  /// Whether server-provided colors participate in theme resolution.
  final bool useApiColors;

  /// Whether full-screen chat uses light (white) status-bar icons and text.
  ///
  /// Enable this for dark or strongly colored chat headers. This setting does
  /// not affect bottom-sheet, dialog, or embedded presentations.
  final bool lightStatusBarIcons;

  /// Default presentation used by [CerqleChat.open].
  final CerqlePresentation presentation;

  /// Whether the controller may publish throttled visitor typing updates.
  final bool enableTyping;

  /// Optional host bridge for image selection and audio recording.
  final CerqleMediaAdapter? mediaAdapter;

  /// Optional receiver for redacted operational diagnostics.
  final CerqleDiagnosticsCallback? diagnostics;

  /// OneSignal App ID used for push notifications.
  final String oneSignalAppId;

  /// Whether OneSignal push notification device registration is enabled.
  final bool enableOneSignal;

  /// Optional session store override. Defaults to secure storage.
  final CerqleSessionStore? sessionStore;
}
