part of 'cerqle_config.dart';

/// Optional visitor profile supplied when a session starts.
///
/// [signature] must be generated by the integrating company's server. The
/// package deliberately redacts every field from [toString].
@immutable
class CerqleUser {
  /// Creates an optional visitor profile.
  const CerqleUser({
    this.externalId,
    this.name,
    this.email,
    this.avatarUrl,
    this.signature,
  });

  /// Stable host-application identifier for the visitor.
  final String? externalId;

  /// Visitor display name.
  final String? name;

  /// Visitor email address.
  final String? email;

  /// Visitor avatar URL.
  final Uri? avatarUrl;

  /// Server-generated HMAC identity signature.
  final String? signature;

  @override
  String toString() =>
      'CerqleUser(externalId: [redacted], name: [redacted], '
      'email: [redacted], avatarUrl: [redacted], signature: [redacted])';
}
